<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SC-IN-37QVGS3" failures="1" tests="12" name="com.test.app.Search" time="361.012" errors="0" timestamp="27 Jun 2024 09:50:54 GMT" skipped="0">
  <testcase classname="com.test.app.Search" name="AQ_TC001_Verify_Ask_a_Question_page_GUI_elements" time="7.046"/>
  <testcase classname="com.test.app.Search" name="AQ_TC002_Create_new_case" time="45.862"/>
  <testcase classname="com.test.app.Search" name="AQ_TC003_Verify_error_message_when_First_name_field_is_empty" time="28.984"/>
  <testcase classname="com.test.app.Search" name="AQ_TC004_Verify_error_message_when_Last_name_field_is_empty" time="28.960"/>
  <testcase classname="com.test.app.Search" name="AQ_TC005_Verify_error_message_when_Email_field_is_empty" time="28.968"/>
  <testcase classname="com.test.app.Search" name="AQ_TC006_Verify_error_message_when_Subject_field_is_empty" time="28.991"/>
  <testcase classname="com.test.app.Search" name="AQ_TC007_Verify_error_message_when_Question_field_is_empty" time="28.963"/>
  <testcase classname="com.test.app.Search" name="AQ_TC008_Verify_error_message_when_Account_dropdown_is_empty" time="29.027"/>
  <testcase classname="com.test.app.Search" name="AQ_TC09_Verify_error_message_when_Firstname_is_specialCharacter" time="35.132"/>
  <testcase classname="com.test.app.Search" name="AQ_TC010_Verify_error_message_when_Lastname_is_specialCharacter" time="35.075"/>
  <testcase classname="com.test.app.Search" name="AQ_TC011_Verify_error_message_when_EmailID_is_invalid" time="35.091"/>
  <testcase classname="com.test.app.Search" name="AQ_TC012_Verify_error_message_when_empty_file_is_attached_for_case_creation" time="28.913">
    <failure message="AQ_TC012_Verification is un successfulorg.openqa.selenium.InvalidArgumentException: invalid argument: File not found : C:\Sample_mini\Demo//src//test//resources//TestData//KaptureCrawlingJIRA_empty.docx
  (Session info: chrome=126.0.6478.127)
Build info: version: &#039;3.14.0&#039;, revision: &#039;aacccce0&#039;, time: &#039;2018-08-02T20:19:58.91Z&#039;
System info: host: &#039;SC-IN-37QVGS3&#039;, ip: &#039;192.168.0.100&#039;, os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;20.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.126 (d36ace6122e..., userDataDir: C:\Users\ABHISH~2\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:58873}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: f5d7b64163fb38645af4e91e7103c71b" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: AQ_TC012_Verification is un successfulorg.openqa.selenium.InvalidArgumentException: invalid argument: File not found : C:\Sample_mini\Demo//src//test//resources//TestData//KaptureCrawlingJIRA_empty.docx
  (Session info: chrome=126.0.6478.127)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'SC-IN-37QVGS3', ip: '192.168.0.100', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.126 (d36ace6122e..., userDataDir: C:\Users\ABHISH~2\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:58873}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: f5d7b64163fb38645af4e91e7103c71b
at org.testng.Assert.fail(Assert.java:96)
at com.test.app.Search_POM.scenarioFailed(Search_POM.java:293)
at com.test.app.Search.AQ_TC012_Verify_error_message_when_empty_file_is_attached_for_case_creation(Search.java:367)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AQ_TC012_Verify_error_message_when_empty_file_is_attached_for_case_creation -->
</testsuite> <!-- com.test.app.Search -->
